#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: autonomousdatabase-sample
spec:
  details:
    autonomousDatabaseOCID: ocid1.autonomousdatabase...
    wallet:
      # Insert a name of the secret where you want the wallet to be stored. The default name is <metadata.name>-instance-wallet.
      name: instance-wallet
      password:
        # The Name of the secret where you want to hold the wallet password. Comment out k8sSecretName and uncomment ociSecretOCID if you pass the wallet password using OCI Secret.
        k8sSecretName: instance-wallet-password
        # The OCID of the OCI Secret that holds the password of the ADMIN account. It should start with ocid1.vaultsecret... .
        # ociSecretOCID: ocid1.vaultsecret...
  # Authorize the operator with API signing key pair. Comment out the ociConfig fields if your nodes are already authorized with instance principal.
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey
